### ISSUE TITLE
Generate better error messages from non-existent commands (or other command run errors) in run_command()

### ISSUE THREAD

**Issue by katsharp** [olx-global/rubiks#46]
## Expected Behavior
Should be able to run rubiks after following the readme

## Actual Behavior
Was unable to run rubiks because (I suspect) I do not have git-crypt installed.

## Steps to Reproduce the Problem

  1. Clone the repo
  1. Try to run Rubiks

## Specifications

  - Platform: Ubuntu 1604
  - Subsystem:

**Comment by katsharp** [comment]
once installing git-crypt I also had to install htpasswd

**Comment by mb-m** [comment]
`htpasswd` is not a function of rubiks, but of the rubiks repository you're trying to run against.

What's the error message when you run rubiks without git-crypt installed

**Comment by katsharp** [comment]
Before installing git-crypt:
```ksharp@IT000100710:~/work/git/openshift-shared-services$ ../rubiks/rubiks generate
Traceback (most recent call last):
  File "../rubiks/rubiks", line 27, in <module>
    main()
  File "../rubiks/rubiks", line 24, in main
    sys.exit(command.Command.run_command())
  File "/home/ksharp/work/git/rubiks/lib/command.py", line 143, in run_command
    rc = cmd_obj.do_run(args.command)
  File "/home/ksharp/work/git/rubiks/lib/command.py", line 174, in do_run
    rc = self.run(nargs)
  File "/home/ksharp/work/git/rubiks/lib/commands/generate.py", line 46, in run
    files = collection.gen_output()
  File "/home/ksharp/work/git/rubiks/lib/load_python.py", line 206, in gen_output
    return self.outputs.write_output()
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 101, in write_output
    return self._write_output_clustered()
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 124, in _write_output_clustered
    uses_policybinding=uses_policybinding,
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 191, in _write_namespace
    p = op.write_file(path)
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 385, in write_file
    content = str(self.cached_yaml)
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 119, in __str__
    return self._internal_render()
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 112, in _internal_render
    ret += self.var[i].__str__()
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 120, in __str__
    return self.renderer(self._internal_render())
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 107, in _internal_render
    ret += self.to_string()
  File "/home/ksharp/work/git/rubiks/lib/kube_vartypes.py", line 27, in to_string
    s = str(self.value)
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 119, in __str__
    return self._internal_render()
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 107, in _internal_render
    ret += self.to_string()
  File "/home/ksharp/work/git/rubiks/lib/kube_vartypes.py", line 102, in to_string
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by katsharp** [comment]
after installing git-crypt, BEFORE install htpasswd (or, more accurately, apache2-utils)

```ksharp@IT000100710:~/work/git/openshift-shared-services$ sudo ../rubiks/rubiks generate
Traceback (most recent call last):
  File "../rubiks/rubiks", line 27, in <module>
    main()
  File "../rubiks/rubiks", line 24, in main
    sys.exit(command.Command.run_command())
  File "/home/ksharp/work/git/rubiks/lib/command.py", line 143, in run_command
    rc = cmd_obj.do_run(args.command)
  File "/home/ksharp/work/git/rubiks/lib/command.py", line 174, in do_run
    rc = self.run(nargs)
  File "/home/ksharp/work/git/rubiks/lib/commands/generate.py", line 46, in run
    files = collection.gen_output()
  File "/home/ksharp/work/git/rubiks/lib/load_python.py", line 206, in gen_output
    return self.outputs.write_output()
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 101, in write_output
    return self._write_output_clustered()
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 124, in _write_output_clustered
    uses_policybinding=uses_policybinding,
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 191, in _write_namespace
    p = op.write_file(path)
  File "/home/ksharp/work/git/rubiks/lib/output.py", line 385, in write_file
    content = str(self.cached_yaml)
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 119, in __str__
    return self._internal_render()
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 112, in _internal_render
    ret += self.var[i].__str__()
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 120, in __str__
    return self.renderer(self._internal_render())
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 107, in _internal_render
    ret += self.to_string()
  File "/home/ksharp/work/git/rubiks/lib/kube_vartypes.py", line 27, in to_string
    s = str(self.value)
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 119, in __str__
    return self._internal_render()
  File "/home/ksharp/work/git/rubiks/lib/var_types.py", line 107, in _internal_render
    ret += self.to_string()
  File "/home/ksharp/work/git/rubiks/lib/kube_vartypes.py", line 102, in to_string
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by mb-m** [comment]
that's to do with the htpasswd (in this particular repository), and we should better trap that, and generate a proper error message - nothing to do with git-crypt that I can tell.

**Comment by katsharp** [comment]
btw it works now that i installed those 2 things
